2024-07-08 23:29:52,279 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2024-07-08 23:29:52,284 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2024-07-08 23:29:52,286 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--format: "value(projectNumber)", PROJECT_ID_OR_NUMBER: "ultra-path-428923-i6"]
2024-07-08 23:29:52,319 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-07-08 23:29:52,372 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/ultra-path-428923-i6?alt=json HTTP/1.1" 403 None
2024-07-08 23:29:52,377 DEBUG    root            Chosen display Format:default
2024-07-08 23:29:52,405 DEBUG    root            Chosen display Format:default
2024-07-08 23:29:52,406 DEBUG    root            Chosen display Format:default
2024-07-08 23:29:52,424 DEBUG    root            Chosen display Format:default
2024-07-08 23:29:52,407 DEBUG    root            (gcloud.projects.describe) [761730578008-compute@developer.gserviceaccount.com] does not have permission to access projects instance [ultra-path-428923-i6] (or it may not exist): Cloud Resource Manager API has not been used in project 761730578008 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=761730578008 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. This command is authenticated as 761730578008-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=761730578008
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/761730578008
    service: cloudresourcemanager.googleapis.com
  reason: SERVICE_DISABLED
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 815, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/surface/projects/describe.py", line 51, in Run
    return projects_api.Get(project_ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 129, in Get
    return client.projects.Get(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 758, in Get
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 734, in _RunMethod
    http_response = http_wrapper.MakeRequest(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 359, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 348, in MakeRequest
    return _MakeRequestNoRetry(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 406, in _MakeRequestNoRetry
    check_response_func(response)
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 243, in _CheckResponse
    _CheckForApiEnablementError(response_as_error)
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 209, in _CheckForApiEnablementError
    PromptToEnableApi(*enablement_info)
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 192, in PromptToEnableApi
    raise exception
googlecloudsdk.api_lib.util.exceptions.HttpException: [761730578008-compute@developer.gserviceaccount.com] does not have permission to access projects instance [ultra-path-428923-i6] (or it may not exist): Cloud Resource Manager API has not been used in project 761730578008 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=761730578008 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. This command is authenticated as 761730578008-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=761730578008
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/761730578008
    service: cloudresourcemanager.googleapis.com
  reason: SERVICE_DISABLED
2024-07-08 23:29:52,426 ERROR    root            (gcloud.projects.describe) [761730578008-compute@developer.gserviceaccount.com] does not have permission to access projects instance [ultra-path-428923-i6] (or it may not exist): Cloud Resource Manager API has not been used in project 761730578008 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=761730578008 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. This command is authenticated as 761730578008-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=761730578008
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/761730578008
    service: cloudresourcemanager.googleapis.com
  reason: SERVICE_DISABLED
